# Generated by Django 5.1.6 on 2025-05-03 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('enseignants', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursesubmission',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_submissions', to='enseignants.course'),
        ),
        migrations.AddField(
            model_name='coursesubmission',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchase',
            name='formation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to='enseignants.formation'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchases', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('student', 'formation')},
        ),
    ]
